name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.0.0
  check_readme:
    name: check_readme
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.x
        env:
          - TOXENV: "check_readme"
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: pre-commit cache
        uses: actions/cache@v1
        with:
          path: .pre-commit
          key: ${{ runner.OS }}-pre-commit
      - name: Install tox
        run: |
          python --version
          python -m pip install --upgrade tox
      - name: Run tox
        run: env PRE_COMMIT_HOME=${GITHUB_WORKSPACE}/.pre-commit python -m tox
        shell: bash
        env: ${{ matrix.env }}
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - 3.x
        env:
          - TOXENV: py3
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python --version
          python -m pip install --upgrade tox
      - name: Run tox
        run: python -m tox
        env: ${{ matrix.env }}
